name: Refresh template list on server
on: 
  workflow_dispatch:
  repository_dispatch:
    types:
      - resource-published
    if: github.event.client_payload.status == '200' && github.event.client_payload.path == '/templates.json'
jobs:
  refresh-template-list-on-server:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Status: ${{ github.event.client_payload.status }}"
        echo "Path: ${{ github.event.client_payload.path }}"
    - run: |
        curl -X GET -f "https://api.kestrelone.com/refreshTemplates" --header "Authorization: Bearer ${{ secrets.MINOR_UPDATES_TOKEN }}"